# Generated by Django 5.0.3 on 2024-03-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_payment'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart_items',
            field=models.ManyToManyField(to='app.cartitem'),
        ),
    ]
