# Generated by Django 5.0.3 on 2024-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Placed', max_length=50),
        ),
    ]
