# Generated by Django 5.0.3 on 2024-04-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_address'),
        ('app', '0003_product_image_blouse_small_product_image_body_small_and_more'),
    ]

    operations = [
    ]
