# Generated by Django 5.0.3 on 2024-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20240416_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='traking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Dispatched', 'Order Dispatched'), ('Order Cancelled', 'Order Cancelled')], default='Placed', max_length=50),
        ),
    ]
