# Generated by Django 5.0.3 on 2024-04-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_traking_id_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='traking_id',
            new_name='tracking_id',
        ),
    ]
