# Generated by Django 5.0.3 on 2024-04-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_address_state_remove_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_blouse',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_body',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_border',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_pallu',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue/'),
        ),
    ]
