# Generated by Django 5.0.3 on 2024-04-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_details',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
