# Generated by Django 5.0.3 on 2024-04-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20240415_1845'),
        ('app', '0007_alter_order_status'),
    ]

    operations = [
    ]
