# Generated by Django 5.0.3 on 2024-04-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20240417_1403'),
        ('app', '0008_order_product_details'),
    ]

    operations = [
    ]
