# Generated by Django 5.0.3 on 2024-04-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20240419_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='catalogue/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image_pallu',
            field=models.ImageField(upload_to='catalogue/'),
        ),
    ]
