# Generated by Django 5.0.3 on 2024-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_cover_image_alter_product_image_pallu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image_small',
            field=models.ImageField(default=1, upload_to='catalogue/'),
            preserve_default=False,
        ),
    ]
