# Generated by Django 5.0.3 on 2024-04-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_order_created_at_remove_order_products_and_more'),
        ('payment', '0003_address_first_name_address_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.address'),
        ),
    ]
